### ISSUE TITLE
Problems with no temperature updates in Domoticz

### ISSUE THREAD

**Issue by miljume** [AlbertHakvoort/Melcloud2Domoticz#1]
Hello,

I have troubles getting the script to run, I have checked my login details but it seems like I am unauthorized in some way

Please see the script output below

root@raspberrypi:/var/bin/melcloud# /var/bin/melcloud/melcloud2domoticz.sh
Melcloud to Domoticz tool version 0.9
json: error: input is not JSON: Unexpected '<' at line 1, column 1:
        <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
        ^
No power changes
Update Power status to On
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Outdoor Temp
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Room Temp
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Heatflow Temp
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Operation mode is 
json: error: input is not JSON: Unexpected '<' at line 1, column 1:
        <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
        ^
Update SWW Temp
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update SWW Setpoint
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Operation Modus to SWW
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Operation Mode to On
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>Update Error Status
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>json: error: input is not JSON: Unexpected '<' at line 1, column 1:
        <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
        ^
No Temp changes are send to Melcloud

**UPDATE: My fault, Domoticz login was turned on!**

**Comment by miljume** [comment]
I correct myself, the reson was the Domoticz login which I forgot about so the script now runs without problems!

Although no temperatures are updated in Domoticz

**Comment by AlbertHakvoort** [comment]
When you run the script in a console, do you get any messages?
