### ISSUE TITLE
Diagnostic information: Unexpected Internal Error 980489945

### ISSUE THREAD

**Issue by miljume** [AlbertHakvoort/Melcloud2Domoticz#2]
When changing IPXWPMODE in Domoticz the script shows the following error:

Operation mode is 
WP Mode Domoticz changed

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
    <style type="text/css">
        BODY, P {
            font-family: sans-serif;
        }
    </style>
</head>
<body>
    <div style="text-align: center">
        <a href="http://www.melcloud.com"><img style="max-width: 100%;" src="/css/assets/logo-wide.png" alt="MELCloud" /></a>
    </div>
    <h1>Unexpected Error</h1>
    
        <p>An unexpected error has occrred. 
        <a href="http://www.melcloud.com">Please return to the home page.</a></p>
    <p>Diagnostic information: Unexpected Internal Error 980489945</p>

</body>
</html>

**Comment by nic27** [comment]
I have the same issue :(

**Comment by miljume** [comment]
I suggest you look at https://www.domoticz.com/forum/viewtopic.php?t=7496 instead. It works much better and I have been running this for several months now

**Comment by nic27** [comment]
I also tested it but I also have an error :( (Error @line 271). Same error already reported on the domoticz forum.

**Comment by AlbertHakvoort** [comment]
The script is been tested with a Air/Water heatpump, maybe the layout of the Air/Air units are different
