### ISSUE TITLE
Temperature not updated in MELCloud

### ISSUE THREAD

**Issue by miljume** [AlbertHakvoort/Melcloud2Domoticz#3]
When updating IDXSETPOINT to a new temperature in Domoticz, the script shows
```
Setpoint Domoticz adjusted
Send setpoint to Melcloud
```
But the temperature is not updated when logging in to MELCloud (https://app.melcloud.com/)

No error message

**Comment by AlbertHakvoort** [comment]
What kind of device you've got? (Air/Air or Air/Water unit?)

**Comment by miljume** [comment]
Air/Air but I have switched to using perl script instead so this is not urgent for me anymore
