### ISSUE TITLE
"ErrorId":1,"ErrorMessage":null

### ISSUE THREAD

**Issue by delwinbest** [AlbertHakvoort/Melcloud2Domoticz#4]
Hi,

Do you know if this API still works? I've been trying using your script and cURL, getting the same error:

"ErrorId":1,"ErrorMessage":null

The following is executed:

/usr/bin/curl -s 'https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin' -H 'Origin: https://app.melcloud.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4,af;q=0.2,de;q=0.2,lt;q=0.2,es;q=0.2' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://app.melcloud.com/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary '{"Email":"$EMAIL","Password":"$PASSWORD","Language":12,"AppVersion":"1.11.2.0","Persist":false,"CaptchaChallenge":null,"CaptchaResponse":null}' --compressed

I get the following reply:

{"ErrorId":1,"ErrorMessage":null,"LoginStatus":0,"UserId":0,"RandomKey":null,"AppVersionAnnouncement":null,"LoginData":null,"ListPendingInvite":null,"ListOwnershipChangeRequest":null,"ListPendingAnnouncement":null,"LoginMinutes":0,"LoginAttempts":0}

**Comment by AlbertHakvoort** [comment]
Hi,

The API still works. What kind of unit do you have?

**Comment by delwinbest** [comment]
I'll test again, at the time, this is what I have:

MAC-559if-e wi-fi control adaptor
MSZ-GL60VFD and MSZ-GL71

**Comment by AlbertHakvoort** [comment]
please try the new version
