### ISSUE TITLE
SWW

### ISSUE THREAD

**Issue by r-g-i-t-h-u-b** [AlbertHakvoort/Melcloud2Domoticz#6]
What is SWW parameter?

**Comment by AlbertHakvoort** [comment]
Haha, I used the dutch abbreviation.. SWW is DHW (Domestic Hot Water)

**Comment by r-g-i-t-h-u-b** [comment]
Thanks

**Comment by r-g-i-t-h-u-b** [comment]
The script change my linguage on MELCloud (italy)

**Comment by AlbertHakvoort** [comment]
To Dutch or English?

**Comment by r-g-i-t-h-u-b** [comment]
To dutch

**Comment by r-g-i-t-h-u-b** [comment]
I change 12 to 19 in last line on script and now is in italy

## Login and get Session key

$CURL -s -o $FOLDER/.session 'https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin' \
-H 'Cookie: policyaccepted=true; gsScrollPos-189=' \
-H 'Origin: https://app.melcloud.com' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Accept-Language: nl-NL,nl;q=0.9,en-NL;q=0.8,en;q=0.7,en-US;q=0.6,de;q=0.5' \
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' \
-H 'Content-Type: application/json; charset=UTF-8' \
-H 'Accept: application/json, text/javascript, */*; q=0.01' \
-H 'Referer: https://app.melcloud.com/' -H 'X-Requested-With: XMLHttpRequest' \
-H 'Connection: keep-alive' --data-binary '{"Email":'"\"$USERNAME\""',"Password":'"\"$PASSWORD\""',"Language":19,"AppVersion":"1.17.3.1","Persist":true,"C$


0	=	en	English
1	=	bg	Български
2	=	cs	Čeština
3	=	da	Dansk
4	=	de	Deutsch
5	=	et	Eesti
6	=	es	Español
7	=	fr	Français
8	=	hy	Հայերեն
9	=	lv	Latviešu
10	=	lt	Lietuvių
11	=	hu	Magyar
12	=	nl	Nederlands
13	=	no	Norwegian
14	=	pl	Polski
15	=	pt	Português
16	=	ru	Русский
17	=	fi	Suomi
18	=	sv	Svenska
19	=	it	Italiano
20	=	uk	Українська
21	=	tr	Türkçe
22	=	el	Ελληνικά
23	=	hr	Hrvatski
24	=	ro	Română
25	=	sl	Slovenščina

**Comment by AlbertHakvoort** [comment]
Thanks, I will add it to the readme!

**Comment by r-g-i-t-h-u-b** [comment]
Why "HeatpumpActive" is a switch and not a text?
Why all objects do not refresh every minute?
